### ISSUE TITLE
Chargement reste bloqué

### ISSUE THREAD

**Issue by Haeresis** [Orchard-ID/CEMEA-PESL-Website#12]
Le message chargement reste bloqué à la première visite

**Comment by albanallee** [comment]
Ne se produit pas que sur mobile, j'ai également pu constater le problème sur Desktop avec le chrome de Fabien (concepteur rédacteur aux Ateliers ETIC)

**Comment by Haeresis** [comment]
Ajout de

```bash
RewriteCond %{HTTPS} off
```

A tous les environnements. À ré-ouvrir si le bug réapparait.
