### ISSUE TITLE
Logo des marques en couleurs

### ISSUE THREAD

**Issue by Haeresis** [Orchard-ID/CEMEA-PESL-Website#15]
Les logos des marques du pied de page, des carousels et dans le titre doivent avoir leurs couleurs originales

**Comment by uhustickone** [comment]
https://github.com/Orchard-ID/CEMEA-PESL-Website/commit/83ad2ca56a43b2146c1ed800ce7366ab5a16a2b8

**Comment by Haeresis** [comment]
Les logos en SVG sont dans des cadres blanc énorme. Il faudrait que le SVG ne contiennent que l'image pour pouvoir le manipuler correctement dans les pages web juste en affectant la width souhaité.

**Comment by Haeresis** [comment]
Les logos en SVG sont dans des cadres blanc énorme @uhustickone. Il faudrait que le SVG ne contiennent que l'image pour pouvoir le manipuler correctement dans les pages web juste en affectant la width souhaité.

**Comment by uhustickone** [comment]
https://github.com/Orchard-ID/CEMEA-PESL-Website/commit/3ea260ea098d3aa20e3ae636c81d04216e24d65d
