### ISSUE TITLE
Fichier à lister via Google Drive

### ISSUE THREAD

**Issue by albanallee** [Orchard-ID/CEMEA-PESL-Website#19]
Mettre des liens explicites pour entreprendre des actions utilisateurs claires
-
Les actions possibles pourraient être :
 - Visualiser
 - Editer
 - Exporter
 - Télécharger

Exemple de lien à utilisable à lister via l'api 

Lien de visualisation permanent de fichiers publics : https://docs.google.com/uc?id=FILE-ID

**Comment by Haeresis** [comment]
https://github.com/Orchard-ID/CEMEA-PESL-Website/commit/f16d5c6956b155dbe1932faabb5ccbc40d4d4963
