### ISSUE TITLE
Favicon CEMÉA incorrecte

### ISSUE THREAD

**Issue by Haeresis** [Orchard-ID/CEMEA-PESL-Website#7]
Pourquoi c'est une icone Orchard ID

![image](https://user-images.githubusercontent.com/3882169/30685883-b9a5d212-9eb6-11e7-9770-361f937c6c0c.png)

**Comment by uhustickone** [comment]
https://github.com/Orchard-ID/CEMEA-PESL-Website/commit/83ad2ca56a43b2146c1ed800ce7366ab5a16a2b8

**Comment by Haeresis** [comment]
👏
